[project]
name = "django-q-dot-import"
version = "0.1.0"
description = "Allow custom imported"
authors = [{ name = "Rory", email = "rory@rory.com" }]
requires-python = ">=3.8"


[project.entry-points."djangoq.errorreporters"]
dot_import = "django_q_dot_import.dot_import:DotImport"
